services:
  - type: web
    name: my-react-app
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    buildFilter:
      paths:
        - "**/*"
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
